### ISSUE TITLE
Add AJAX to webpage for displaying and changing data

### ISSUE THREAD

**Issue by shmick** [shmick/PID-Controller#1]
For the ```controller-wemos_d1_mini-oled.ino``` sketch

1) PID Ouput ( Output )
2) Current Set Point ( Setpoint )

I'd also like to be able to change:
1) the value of **Setpoint**
2) the boolean state of **operMode**

**Comment by xpokor02** [comment]
Hi ,
Did you finished code for changing Setpoint?
I tried to use your code but had to change relay pin to 15 (it is off when powering wemos) and IC pins to default so display works.
// Setup I2C pins
#define ESP_SDA 4 
#define ESP_SCL 5 
Now I wanted to figure out how you are controlling pid via web and found this.
Thanks

**Comment by shmick** [comment]
For changing setpoint I'm using a basic POST call right now ie: 

```curl -d "sp=105" http://espresso.local/set```

The code is at https://github.com/shmick/Espresso-PID-Controller/blob/master/controller-iotwebconf.ino#L459-L489

**Comment by xpokor02** [comment]
Thank you for that, I saw function, but I initially forgot to specify method
```
<form action="/set" method="post">
  Setpoint:<br>
  <input type="number" name="sp" value="105"><br>
  <input type="submit" value="Submit">
  <input type="reset">
</form>
```
Works for me.
