### ISSUE TITLE
Change setpoint

### ISSUE THREAD

**Issue by felix5411** [shmick/PID-Controller#13]
Hi, and thanks for the code!
Just installed everyting and it seems to work fine, have not tried MQTT yet.
Is it possible to change the set temp for the boiler via the webpage? I tried to access "/set" but it gives me "Requested a non-excisting page". Would be really nice to start expemimenting with temperature and coffee brewing as well :)

Is it easy to merge your project with the MQTT functionality that is available in one off the forks of your project? Web page would be prefered tho.

Also, had a bit of problem verifying the code. I had to use an older version of "IotWebConf" library. I think it was 3.0.0, can't figure out how to see what version I had installed now. Maby a good thing to add to the dok /comments in code?

**Comment by shmick** [comment]
Hi @felix5411,

Thanks for hanging in there with the needed changes. I'll look into what's needed to update the code to work with the latest IotWebConf library.

You need use the [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) method to perform a set. An example with curl would be `curl -d "sp=105" "http://<ip address of wemos>/set"`

**Comment by shmick** [comment]
@felix5411 I've just pushed an update to enable setting Setpoint and steamMode via MQTT
