### ISSUE TITLE
Homeassistant cards

### ISSUE THREAD

**Issue by xconverge** [shmick/PID-Controller#7]
First, wanted to say thanks, you saved me a TON of time with this project :) I added PID autotuning and some EEPROM storage, but besides that, I have some very similar needs/desires as your project, I probably could have just used yours exactly as is but wanted to build it up as I went. I wanted to stop my waiting around/temp surfing, but overall have the exact same buttons/interface, without needing to fiddle with anything once it was setup and installed within the machine.

https://github.com/xconverge/gaggia-pid/blob/main/project/project.ino

Second, you might want to add   unit_of_measurement: 'degrees' to your sensor.yaml for the temps, this allows you to have nice plots if you wanted. I plan on using the mqtt data to tune PID a bit, then will probably turn mqtt off.

but mostly just wanted to say thanks!

**Comment by shmick** [comment]
You're very welcome. Glad my efforts can help others on their way to great coffee. 

Thanks for the tip about the HA cards, I'll look into that. My personal preference is to use HA to simply control the on/off state and check if the machine is ready.
